// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LeaderboardManager
{
        public const string achievement_over_20 = "CgkInoic2v4REAIQAw"; // <GPGSID>
        public const string leaderboard_scoreboard = "CgkInoic2v4REAIQBw"; // <GPGSID>
        public const string achievement_trumped_the_wall = "CgkInoic2v4REAIQBg"; // <GPGSID>
        public const string achievement_over_50 = "CgkInoic2v4REAIQBA"; // <GPGSID>
        public const string achievement_first_game = "CgkInoic2v4REAIQAg"; // <GPGSID>
        public const string leaderboard_hardmode = "CgkInoic2v4REAIQCQ"; // <GPGSID>
        public const string achievement_over_150 = "CgkInoic2v4REAIQBQ"; // <GPGSID>

}

